config/routes.rb
Rails.application.routes.draw do

  root to: 'search#index', as: 'search'
  resources :curriculums

  resources :docs

end

app/models/curriculum.rb
require 'nokogiri'
require 'magic'
require 'stringio'
require 'tmpdir'

class Curriculum < ActiveRecord::Base

  validates_uniqueness_of :identifier

  def self.build(data)
    self.new.tap do |curriculum|
      curriculum.send :read!, data
    end
  end

  def self.search(query)
    # FIXME THIS IS HORRIBLE. Use full text search instead!
    like_expr = ['%', query.downcase, '%'].join
    self.where(['lower(name) LIKE ?', like_expr])
  end

  def data
    self[:data]
  end
  private :data

  def sanitized_data
    doc = Nokogiri::XML(data)

    doc.css('ENDERECO-RESIDENCIAL').remove
    d = doc.css('DADOS-GERAIS')
    [
      'NOME-DO-PAI',
      'NOME-DA-MAE',
      'DATA-NASCIMENTO',
      'CPF',
      'SEXO',
      'RACA-OU-COR',
      'NUMERO-IDENTIDADE',
      'ORGAO-EMISSOR',
      'UF-ORGAO-EMISSOR',
      'DATA-DE-EMISSAO',
      'NUMERO-DO-PASSAPORTE',
    ].each do |attr|
      d.attribute(attr).remove
    end

    doc.to_s
  end

  protected

  def read!(io)
    self.data = io.read

    filename = io.original_filename
    mime_type = Magic.guess_string_mime(data)
    if filename =~ %r{\.xml$}i || mime_type =~ %r{xml}
      # nothing
    elsif filename =~ %r{\.zip$}i || mime_type =~ %r{/zip}
      Dir.mktmpdir do |dir|
        Dir.chdir(dir) do
          File.open('the.zip', 'wb') { |f| f.write(data) }
          system('unzip -qq the.zip 2>/dev/null')
          xml = Dir.glob('*.{XML,xml}')
          if xml.size != 1
            raise ArgumentError.new(_('Um arquivo ZIP deve conter um, e apenas um, arquivo XML'))
          end
          self.data = File.read(xml.first, encoding: Encoding::ASCII_8BIT)
        end
      end
    else
      raise ArgumentError.new(_('Apenas formatos XML e ZIP são suportados; %s não') % mime_type)
    end

    process_xml
  end

  def process_xml
    document = Nokogiri::XML(data)

    # Identifier
    cv_data = document.css('CURRICULO-VITAE')
    self.identifier = cv_data.attribute('NUMERO-IDENTIFICADOR').value
    time_str = cv_data.attribute('DATA-ATUALIZACAO').value + cv_data.attribute('HORA-ATUALIZACAO').value
    self.last_update = Date.strptime(time_str, '%d%m%Y%H%M%s')

    # Personal information
    personal_info = document.css('DADOS-GERAIS')
    self.name = personal_info.attribute('NOME-COMPLETO').value

    # Abstract
    abstract = document.css('RESUMO-CV')
    self.abstract = abstract.attribute('TEXTO-RESUMO-CV-RH').value

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  protected

  def set_locale
    I18n.locale = 'pt-BR' # FIXME allow at least English
  end
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController

  def index
    redirect_to action: 'new'
  end

  def show
    @curriculum = Curriculum.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { send_data @curriculum.sanitized_data, content_type: 'application/xml', disposition: 'attachment' }
      format.json { render json: @curriculum }
    end
  end

  def new
    @curriculum = Curriculum.new
  end

  def create
    @curriculum = Curriculum.build(params[:data])
    @curriculum.save!
  rescue
    render action: 'new'
  end

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  def show
    render action: params[:id].underscore
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params[:q]
      @curriculums = Curriculum.search(params[:q])
      if params[:feeling_lucky]
        redirect_to curriculum_path(@curriculums.first)
      end
    else
      @curriculum_count = Curriculum.count
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/create.slim
h1
  = _('Obrigado pela sua contribuição!')

p
  = _('Em alguns segundos você poderá buscar o seu currículo.')
  = link_to _('Buscar agora'), search_path

app/views/curriculums/new.slim
h1 Adicionar currículo

- if @curriculum.errors.present?
  div.errors
    p
      strong= _('Oops, não foi possível adicionar o este currículo!')
    ul
      - @curriculum.errors.full_messages.each do |e|
        li== e
- else

  p
    .badge 1
    a href=doc_path('lattes-export') Exportar currículo no Lattes

  p
    .badge 2
    ' Fazer upload no Librelattes

= form_for @curriculum, html: { multipart: true }

  .upload
    .file-explanation= _('Currículo Lattes (.xml ou .zip)')
    .file-select
      = file_field_tag :data

  = submit_tag _('Fazer upload')

app/views/curriculums/show.slim
h1= @curriculum.name

p
  a.download href=curriculum_path(@curriculum, format: 'xml')
    span
    '  Download XML

blockquote= @curriculum.abstract

/ FIXME
div.alert.alert-warning
  p
    strong= _('Em construção!')
    == '&nbsp;'
    = _('Mais informações do currículo serão exibidas em breve!')

app/views/docs/lattes_export.slim
h1 Exportando o seu currículo Lattes

p
  .badge 1

  | Acesse o 
  a href="http://lattes.cnpq.br" target="_blank" site de atualização do currículo Lattes
  | , e procure a opção “Atualizar currículo”.


a href="http://lattes.cnpq.br" target="_blank"

  = image_tag 'lattes-01.png'

p
  .badge 2

  span Entre com o seu CPF e sua senha do sistema Lattes

= image_tag 'lattes-02.png'

p
  .badge 3
  span Selecione a a opção "Exportar" na barra lateral à esquerda

= image_tag 'lattes-03.png'

p
  .badge 4
  span Escolha a opção "XML" para exportação

= image_tag 'lattes-04.png'

p
  .badge 5
  span Salve o arquivo fornecido pelo Lattes, e faça o upload na base de dados do Librelattes

.upload-link

  = link_to _('Fazer upload no Librelattes'), new_curriculum_path

app/views/docs/terms_of_use.slim
h1 Termos de Uso

p Ao usar o Librelattes, você está implicitamente aceitando os seguintes termos
  de uso. No texto, abaixo, VOCÊ se refere a todo usuário do Librelattes, e NÓS
  se refere à equipe responsáve pelo Librelattes.

h2 1. Direitos e obrigações do usuário

p 1.1. VOCÊ se compromete a fornece apenas informações verdadeiras.

p 1.2. VOCÊ se compromete a fornecer apenas suas próprias informações, ou informações este já estejam públicas de qualquer forma.

h2 2. Direitos e obrigações da equipe Librelattes

p 2.1. NÓS não divulgaremos informações que o Lattes também não divulga. Isto inclui, mas não está limitado, a:

ol type='a'
  li endereço residencial;
  li telefone residencial;
  li filiação;
  li ano de nascimento;
  li CPF;
  li sexo;
  li cor ou raça;
  li identidade;
  li passaporte e
  li endereços eletrônicos.

p 2.1.1. Estas informações estão presentes nos arquivos exportados pelo Lattes, e são armazenadas no Librelattes.

p 2.2.2. O arquivo XML exportado pelo Librelattes tem estas informações removidas automaticamente antes da exportação.

h2 3. Sobre estes termos de uso

p 3.1 Novas versões deste termo de uso podem ser publicadas pela equipe do
  Librelattes, e passarão a valer, inclusive retroativamente, para usuários que
  tenham aceito versões anteriores.

p 3.2 NÓS nos comprometemos a não fazer mudanças nos termos de
  uso que restrinjam o acesso aos dados hospedados, ou o seu uso.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Debian Continuous Integration Results">
    <meta name="author" content="The Debian Project">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Librelattes</title>
    <%#<link rel="icon" type="image/png" href=".."/>%><%# FIXME %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id='wrap'>

      <!-- Fixed navbar -->
      <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand hidden-xs" href="/">Librelattes</a><%# TODO small screen logo %>
          <a class="navbar-brand visible-xs" href="/">Librelattes</a><%# TODO large screen logo %>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to _('Buscar currículos'), search_path %>
              <li><%= link_to _('Enviar currículo'), new_curriculum_path %>
              <li><%= link_to _('Termos de uso'), doc_path('terms_of_use') %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <div class='container <%= params[:controller] %>'>
        <%= yield %>
      </div>

      <footer>
        <div class='container'>
          <p class='text-muted credit'>
          Librelattes - Copyright © the Librelattes development team. This is
          free software licensed under the GNU Affero General Public License
          version 3 or later. Source code on
          <a href="https://gitlab.com/terceiro/librelattes">git repository</a>
          </p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/search/index.slim
- unless @curriculums
  .welcome-message
    h1= _('Bem-vindo ao Librelattes')
    p== _('O Librelattes é uma iniciativa para criar uma base de dados alternativa, e principalmente aberta, de currículos. Para participar, você pode <a href="%s">exportar o seu currículo na plataforma Lattes</a>, e fazer o <a href="%s">upload</a> dele aqui.') % [doc_path('lattes-export'), new_curriculum_path]

div.search

  h2= _('Buscar currículos')
  - if @curriculum_count
    = _('Currículos disponíveis: %d') % @curriculum_count

  = form_tag({}, method: 'get', enforce_utf8: false)
    = text_field_tag :q, params[:q]

    .buttons

      = submit_tag _('Buscar'), name: nil
      = submit_tag _('Estou com sorte'), name: 'feeling_lucky', title: _('Redireciona você para o primeiro currículo que case com a sua busca')

- if @curriculums
  .results

    .summary
      = _('Currículos encontrados: %d') % @curriculums.count

    - @curriculums.each do |curriculum|
      div.curriculum
        .name= link_to curriculum.name, curriculum_path(curriculum)
        .abstract= curriculum.abstract